Updated RISC-V intrinsics to match LLVM 17.0.2
sifive/sifive-blis pull request #5
Opened 2023-10-13 20:37 UTC by Aaron-Hutchinson

2023-10-13 22:01 UTC, nick-knight requested changes

2023-10-13 22:01 UTC, nick-knight commented on kernels/sifive_x280/riscv_overloaded_intrinsics.h
> +#define RVV_TYPE_FX_(PRECISION, LMUL, GROUPS) vfloat##PRECISION##LMUL##x##GROUPS##_t
Suggest using `NFIELDS` instead of `GROUPS`, to match ISA spec.

2023-10-13 22:16 UTC, Aaron-Hutchinson commented on kernels/sifive_x280/riscv_overloaded_intrinsics.h
> +#define RVV_TYPE_FX_(PRECISION, LMUL, GROUPS) vfloat##PRECISION##LMUL##x##GROUPS##_t
Done!

2023-10-14 02:23 UTC, nick-knight approved these changes

2023-10-14 02:39 UTC, merged